# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v-2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: GitHub Action for yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
       cmd: install # npm install
    - name: creating build
      run: yarn build
    - name: installing surge
      run: mpn install -g surge
      
    - name: deploying on surge
      run: surge .build http://bootcamp_session2.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
